[NETWORK ERROR] https://olm-s3.s3.eu-west-1.amazonaws.com/2018/11/03/UrCL0ld6ePFExmgRQhrHnG46posXiwQcoFOGGIV8.jpeg: HTTPSConnectionPool(host='olm-s3.s3.eu-west-1.amazonaws.com', port=443): Max retries exceeded with url: /2018/11/03/UrCL0ld6ePFExmgRQhrHnG46posXiwQcoFOGGIV8.jpeg (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001B10ADF8370>: Failed to resolve 'olm-s3.s3.eu-west-1.amazonaws.com' ([Errno 11001] getaddrinfo failed)"))
